"""
Django settings for trendcrafters project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import os
from django.core.management.utils import get_random_secret_key
from decouple import config

# -----------------------------------------------------------
# BASE DIRECTORY
# -----------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# -----------------------------------------------------------
# SECURITY SETTINGS
# -----------------------------------------------------------
DEBUG = config('DEBUG', default=False, cast=bool)
# Production must set DJANGO_SECRET_KEY (a random per-process key would break signed cookies
# across gunicorn workers/restarts). A throwaway key is only allowed in DEBUG.
SECRET_KEY = config('DJANGO_SECRET_KEY', default=get_random_secret_key() if DEBUG else '')
if not SECRET_KEY:
    raise RuntimeError('DJANGO_SECRET_KEY must be set when DEBUG is False (see .env.example).')

ALLOWED_HOSTS = [h.strip() for h in config(
    'ALLOWED_HOSTS',
    default='localhost,127.0.0.1,trendcrafters.global,www.trendcrafters.global'
).split(',') if h.strip()]

# During local development it's convenient to allow all hosts when DEBUG is True
# so accessing the dev server via LAN IPs (e.g. 192.168.x.x) works without raising
# DisallowedHost. In production DEBUG should be False and ALLOWED_HOSTS should be
# set explicitly via environment variables.
if DEBUG:
    # Allow any host in development only
    ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    'https://trendcrafters.global',
    'https://www.trendcrafters.global',
]

# -----------------------------------------------------------
# APPLICATION DEFINITION
# -----------------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.contenttypes',
    'django.contrib.messages',
    'main.apps.StaticFilesConfig',  # django.contrib.staticfiles + ignores Tailwind source
    'django.contrib.sitemaps',
    'main',  # Your main app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For static files in production
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'main.middleware.SeoSyncMiddleware',
]

# No admin panel, no accounts - this is a marketing site with a single contact-form
# endpoint, so django.contrib.admin/auth/sessions are dropped entirely. Flash messages
# from the contact view use cookie storage below instead of the session-backed default.
MESSAGE_STORAGE = 'django.contrib.messages.storage.cookie.CookieStorage'

ROOT_URLCONF = 'trendcrafters.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'main', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.messages.context_processors.messages',
                'main.context_processors.reels',
            ],
        },
    },
]

WSGI_APPLICATION = 'trendcrafters.wsgi.application'

# -----------------------------------------------------------
# DATABASE
# -----------------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': config('DATABASE_PATH', default=str(BASE_DIR / 'db.sqlite3')),
    }
}

# -----------------------------------------------------------
# PASSWORD VALIDATION
# -----------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# -----------------------------------------------------------
# INTERNATIONALIZATION
# -----------------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# -----------------------------------------------------------
# STATIC FILES
# -----------------------------------------------------------
STATIC_URL = '/static/'
# main/static is picked up automatically via the 'main' app (AppDirectoriesFinder).
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Django 5.1+ removed STATICFILES_STORAGE; hashed + compressed files come from whitenoise.
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage' if DEBUG
        else 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# -----------------------------------------------------------
# EMAIL CONFIGURATION
# -----------------------------------------------------------
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='trendcraftersglobal@gmail.com')
# No hardcoded fallback: this was previously a leaked Gmail app password checked into
# source control. Requires EMAIL_HOST_PASSWORD to be set via environment/.env; rotate
# the Gmail app password (the old one is exposed in git history) before deploying.
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

# -----------------------------------------------------------
# SECURITY ENHANCEMENTS (PRODUCTION)
# -----------------------------------------------------------
# HTTPS is terminated by nginx / the AWS load balancer, which sets X-Forwarded-Proto.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=not DEBUG, cast=bool)
SECURE_REDIRECT_EXEMPT = [r'^health/$']  # load-balancer health checks arrive over plain HTTP
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
X_FRAME_OPTIONS = 'DENY'
if not DEBUG:
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31536000, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# -----------------------------------------------------------
# CACHE SETTINGS
# -----------------------------------------------------------
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}

# -----------------------------------------------------------
# LOGGING CONFIGURATION
# -----------------------------------------------------------
LOG_DIR = Path(config('LOG_DIR', default=str(BASE_DIR / 'logs')))
LOG_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': LOG_DIR / 'django.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'main': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# -----------------------------------------------------------
# DEFAULT AUTO FIELD
# -----------------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
